pub mod commit_metadata_ingress_repository_impl;
pub mod commit_repository_impl;
pub mod commit_summary_repository_impl;
pub mod full_commit_summary_history_repository_impl;
pub mod gitextra_write_repository_impl;
pub mod tag_write_repository_impl;
pub mod version_repository_impl;
